[package]
name = "remu"
version = "0.1.0"
authors = ["Michael Khryashchev <me@xiberfix.dev>"]
edition = "2021"

[dependencies]
eframe = { version = "0.23.0", default-features = false, features = ["default_fonts", "wgpu"] }
